@startuml
hide footbox

Subscriber --> Subscription : request(n)
Subscription --> Publisher


loop until done
    alt success
        Publisher --\\ Subscriber : onNext(item)
    else error
        Publisher --\\ Subscriber : onError(x)
    end
end
Publisher --\\ Subscriber : onComplete
@enduml
